from typing import Optional

from fastapi import HTTPException
from sqlalchemy.orm import Session

from backend.data import ticket_repository
from backend.data.database import SessionLocal
from backend.models import TicketCreate, TicketUpdate


def _to_dict(ticket) -> dict:
    """Convert a Ticket ORM row to the dict shape the API layer expects."""
    return {
        "id": ticket.id,
        "customer_name": ticket.customer_name,
        "subject": ticket.subject,
        "message": ticket.message,
        "status": ticket.status,
    }


def get_all_tickets(session: Optional[Session] = None):
    """Return all tickets as a list of dicts."""
    session = session or SessionLocal()
    try:
        tickets = ticket_repository.list_tickets(session)
        return [_to_dict(ticket) for ticket in tickets]
    finally:
        session.close()


def get_ticket_by_id(ticket_id: int, session: Optional[Session] = None):
    """Return a single ticket as a dict, or 404 if not found."""
    session = session or SessionLocal()
    try:
        ticket = ticket_repository.get_ticket(session, ticket_id)
        if ticket is None:
            raise HTTPException(status_code=404, detail="Ticket not found")
        return _to_dict(ticket)
    finally:
        session.close()


def create_ticket(ticket: TicketCreate, session: Optional[Session] = None):
    """Create a new ticket; the ID is generated by PostgreSQL."""
    session = session or SessionLocal()
    try:
        created = ticket_repository.create_ticket(
            session,
            customer_name=ticket.customer_name,
            subject=ticket.subject,
            message=ticket.message,
        )
        session.commit()
        return _to_dict(created)
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()


def update_ticket(
    ticket_id: int,
    updated_ticket: TicketUpdate,
    session: Optional[Session] = None,
):
    """Update only the provided fields of an existing ticket, or 404."""
    session = session or SessionLocal()
    try:
        updates = {}
        if updated_ticket.customer_name is not None:
            updates["customer_name"] = updated_ticket.customer_name
        if updated_ticket.subject is not None:
            updates["subject"] = updated_ticket.subject
        if updated_ticket.message is not None:
            updates["message"] = updated_ticket.message
        if updated_ticket.status is not None:
            updates["status"] = updated_ticket.status

        updated = ticket_repository.update_ticket(session, ticket_id, **updates)
        if updated is None:
            raise HTTPException(status_code=404, detail="Ticket not found")
        session.commit()
        return _to_dict(updated)
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()


def delete_ticket(ticket_id: int, session: Optional[Session] = None):
    """Delete a ticket by ID, or 404 if not found."""
    session = session or SessionLocal()
    try:
        deleted = ticket_repository.delete_ticket(session, ticket_id)
        if not deleted:
            raise HTTPException(status_code=404, detail="Ticket not found")
        session.commit()
        return {"message": "Ticket deleted"}
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()
