"""Data-access layer for tickets.

This repository is the only place that performs SQLAlchemy database access
for tickets. It returns ORM ``Ticket`` objects (or ``None``/``bool`` to signal
a missing row) so the service layer can decide what that means.

Each function takes a SQLAlchemy ``Session``; committing is left to the
caller. The methods only ``flush()`` so that generated values (like a new
``id``) are available and errors surface early.
"""

from sqlalchemy.orm import Session

from backend.data.db_models import Ticket

# Fields the current application supports updating.
UPDATABLE_FIELDS = ("customer_name", "subject", "message", "status")


def list_tickets(session: Session):
    """Return all tickets, ordered by id."""
    return session.query(Ticket).order_by(Ticket.id).all()


def get_ticket(session: Session, ticket_id: int):
    """Return a single ticket by its id, or ``None`` if it does not exist."""
    return session.get(Ticket, ticket_id)


def create_ticket(session: Session, *, customer_name: str, subject: str, message: str):
    """Create a new ticket.

    The ``id`` is generated by the database, and ``status`` defaults to the
    model's default (``\"open\"``).
    """
    ticket = Ticket(
        customer_name=customer_name,
        subject=subject,
        message=message,
    )
    session.add(ticket)
    session.flush()
    return ticket


def update_ticket(
    session: Session,
    ticket_id: int,
    *,
    customer_name=None,
    subject=None,
    message=None,
    status=None,
):
    """Update an existing ticket with only the provided fields.

    Returns the updated ``Ticket``, or ``None`` if the ticket does not exist.
    """
    ticket = session.get(Ticket, ticket_id)
    if ticket is None:
        return None

    if customer_name is not None:
        ticket.customer_name = customer_name
    if subject is not None:
        ticket.subject = subject
    if message is not None:
        ticket.message = message
    if status is not None:
        ticket.status = status

    session.flush()
    return ticket


def delete_ticket(session: Session, ticket_id: int) -> bool:
    """Delete a ticket by its id.

    Returns ``True`` if a ticket was deleted, ``False`` if it did not exist
    (so the service layer can raise a 404).
    """
    ticket = session.get(Ticket, ticket_id)
    if ticket is None:
        return False
    session.delete(ticket)
    session.flush()
    return True