create schema support;

create table support.payments (
    payment_id varchar(64) primary key,
    status text not null,
    amount numeric(12, 2) not null,
    currency varchar(3) not null,

    constraint payments_payment_id_format
        check (payment_id ~ '^PAY-[A-Za-z0-9]+$'),
    constraint payments_status_valid
        check (status in ('pending', 'authorized', 'captured', 'failed', 'refunded', 'cancelled')),
    constraint payments_amount_nonnegative
        check (amount >= 0),
    constraint payments_currency_uppercase
        check (currency ~ '^[A-Z]{3}$')
);

create table support.orders (
    order_id varchar(64) primary key,
    product text not null,
    status text not null,
    payment_id varchar(64) not null unique,

    constraint orders_order_id_format
        check (order_id ~ '^ORD-[A-Za-z0-9]+$'),
    constraint orders_product_not_blank
        check (btrim(product) <> ''),
    constraint orders_status_valid
        check (status in ('pending', 'processing', 'shipped', 'delivered', 'cancelled')),
    constraint orders_payment_id_fk
        foreign key (payment_id)
        references support.payments (payment_id)
        on update restrict
        on delete restrict
);

create table support.tickets (
    id bigint generated by default as identity primary key,
    customer_name text not null,
    subject text not null,
    message text not null,
    status text not null default 'open',
    created_at timestamptz not null default now(),

    constraint tickets_customer_name_not_blank
        check (btrim(customer_name) <> ''),
    constraint tickets_subject_not_blank
        check (btrim(subject) <> ''),
    constraint tickets_message_not_blank
        check (btrim(message) <> ''),
    constraint tickets_status_valid
        check (status in ('open', 'pending', 'resolved'))
);
